"""Add conversation_history

Revision ID: b17c65911c7c
Revises: 311cec4f2a28
Create Date: 2025-04-24 08:24:48.124248

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b17c65911c7c"
down_revision: Union[str, None] = "311cec4f2a28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("goal", sa.Column("conversation_history", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("goal", "conversation_history")
    # ### end Alembic commands ###
